# Generated by Django 5.0.7 on 2024-08-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_is_verify_doctorprofile_is_profile_verify'),
        ('appoinment', '0002_timeslot_remove_slot_end_time_remove_slot_start_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Booking',
        ),
    ]
