# Generated by Django 5.0.7 on 2024-08-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0003_rename_appointment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoinment.timeslot'),
        ),
    ]
