# Generated by Django 5.0.7 on 2024-08-21 15:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0009_alter_booking_doctor_alter_booking_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(choices=[('new_consultation', 'New Consultation'), ('prescription', 'Prescription Request'), ('follow_up', 'Follow-up Appointment')], default='new_consultation', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule_date',
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
