# Generated by Django 5.0.7 on 2024-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
