# Generated by Django 5.0.6 on 2024-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
