# Generated by Django 5.0.6 on 2024-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
