# Generated by Django 5.0.6 on 2024-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_doctorprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
