# Generated by Django 5.0.6 on 2024-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_doctorprofile_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(default='image.jpg', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificates_degrees',
            field=models.FileField(default='certificates_degrees', upload_to='documents/certificates_degrees/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='curriculum_vitae',
            field=models.FileField(default='curriculum_vitae', upload_to='documents/cv/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='identification_document',
            field=models.FileField(default='identification_document', upload_to='documents/identification_documents/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_certificate',
            field=models.FileField(default='medical_license_certificate', upload_to='documents/medical_license_certificates/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='proof_of_work',
            field=models.FileField(default='proof_of_work', upload_to='documents/proof_of_work/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization_certificates',
            field=models.FileField(default='specialization_certificates', upload_to='documents/specialization_certificates/'),
        ),
    ]
