# Generated by Django 5.0.6 on 2024-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_doctorprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(default='image.jpg', upload_to='profile/patient'),
        ),
    ]
