# Generated by Django 5.0.6 on 2024-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_patientprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_verify',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50),
        ),
    ]
