# Generated by Django 5.0.6 on 2024-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_doctorprofile_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificates_degrees',
            field=models.FileField(null=True, upload_to='documents/certificates_degrees/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='curriculum_vitae',
            field=models.FileField(null=True, upload_to='documents/cv/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='identification_document',
            field=models.FileField(null=True, upload_to='documents/identification_documents/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_certificate',
            field=models.FileField(null=True, upload_to='documents/medical_license_certificates/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='proof_of_work',
            field=models.FileField(null=True, upload_to='documents/proof_of_work/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization_certificates',
            field=models.FileField(null=True, upload_to='documents/specialization_certificates/'),
        ),
    ]
