# Generated by Django 5.0.6 on 2024-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_doctorprofile_certificates_degrees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
