# Generated by Django 5.0.6 on 2024-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_doctorprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
