# Generated by Django 5.0.7 on 2024-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_doctorprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile/patient'),
        ),
    ]
