# Generated by Django 5.0.7 on 2024-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
