# Generated by Django 5.0.7 on 2024-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_patientprofile_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
