# Generated by Django 5.0.7 on 2024-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_doctorprofile_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_block',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_block',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
