# Generated by Django 5.0.7 on 2024-08-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_doctorprofile_is_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='is_verify',
            new_name='is_profile_verify',
        ),
    ]
