# Generated by Django 5.0.7 on 2024-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
