# Generated by Django 5.0.7 on 2024-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_doctorprofile_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
