# Generated by Django 5.0.7 on 2024-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_status',
            field=models.CharField(choices=[('not_refunded', 'Not Refunded'), ('refunded', 'Refunded')], default='not_refunded', max_length=20),
        ),
    ]
