# Generated by Django 5.0.7 on 2024-09-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
