# Generated by Django 5.0.7 on 2024-08-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
